### PR TITLE
chore: test fixes

### LINKED ISSUE #1004: Fix Tests in v2 release
**Describe the bug**

Since the `release-v2` branch did not have CI setup, any PRs merged did not run the tests, so tests that were failing were not detected. Failure in tests is due to the epoch length being changed on contracts which was not reflected in the test suite

### PR DESCRIPTION
**Pull request by SamAg19**
fixes #1004

### CODE REVIEW

**Comment by yohanelly95** [comment]
change to `v2.0.1` in package json

File: test/AssignCollectionsRandomly.js [hunk 1]
```diff
@@ -87,6 +87,8 @@ describe('AssignCollectionsRandomly', function () {
         }
       }
 
+      console.log('Jobs Created');
```
Comment (yohanelly95) [inline test/AssignCollectionsRandomly.js:90]: @SamAg19 can you remove the console logs

**Review by yohanelly95 — APPROVED** [review]

**Review by rajkharvar — APPROVED** [review]
